/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day10;

/**
 *
 * @author jlapi
 */
public class TicTacToe extends javax.swing.JFrame {

    private String StartGame = "X";

    public void chooseAPlayer() {

        if (StartGame.equalsIgnoreCase("X")) {
            StartGame = "O";
        } else {
            StartGame = "X";
        }
    }

    public void disableButtons() {
        bn1.setEnabled(false);
        bn2.setEnabled(false);
        bn3.setEnabled(false);
        bn4.setEnabled(false);
        bn5.setEnabled(false);
        bn6.setEnabled(false);
        bn7.setEnabled(false);
        bn8.setEnabled(false);
        bn9.setEnabled(false);
    }

    public void gameOptions() {
        String Button1 = bn1.getText();
        String Button2 = bn2.getText();
        String Button3 = bn3.getText();
        String Button4 = bn4.getText();
        String Button5 = bn5.getText();
        String Button6 = bn6.getText();
        String Button7 = bn7.getText();
        String Button8 = bn8.getText();
        String Button9 = bn9.getText();

        if (Button1 == "X" && Button2 == "X" && Button3 == "X") {

            display.setText("Player X wins!!!");
            disableButtons();

        }

        if (Button1 == "O" && Button2 == "O" && Button3 == "O") {

            display.setText("Player O wins!!!");
            disableButtons();
        }

        if (Button4 == "X" && Button5 == "X" && Button6 == "X") {

            display.setText("Player X wins!!!");
            disableButtons();
        }

        if (Button4 == "O" && Button5 == "O" && Button6 == "O") {

            display.setText("Player O wins!!!");
            disableButtons();
        }

        if (Button7 == "X" && Button8 == "X" && Button9 == "X") {

            display.setText("Player X wins!!!");
            disableButtons();
        }

        if (Button7 == "O" && Button8 == "O" && Button9 == "O") {

            display.setText("Player O wins!!!");
            disableButtons();
        }

        if (Button1 == "X" && Button5 == "X" && Button9 == "X") {

            display.setText("Player X wins!!!");
            disableButtons();
        }

        if (Button1 == "O" && Button5 == "O" && Button9 == "O") {

            display.setText("Player O wins!!!");
            disableButtons();
        }

        if (Button3 == "X" && Button5 == "X" && Button7 == "X") {

            display.setText("Player X wins!!!");
            disableButtons();
        }

        if (Button3 == "O" && Button5 == "O" && Button7 == "O") {

            display.setText("Player O wins!!!");
            disableButtons();
        }

        if (Button1 == "X" && Button4 == "X" && Button7 == "X") {

            display.setText("Player X wins!!!");
            disableButtons();
        }

        if (Button1 == "O" && Button4 == "O" && Button7 == "O") {

            display.setText("Player O wins!!!");
            disableButtons();
        }

        if (Button2 == "X" && Button5 == "X" && Button8 == "X") {

            display.setText("Player X wins!!!");
            disableButtons();
        }

        if (Button2 == "O" && Button5 == "O" && Button8 == "O") {

            display.setText("Player O wins!!!");
            disableButtons();
        }

        if (Button3 == "X" && Button6 == "X" && Button9 == "X") {

            display.setText("Player X wins!!!");
            disableButtons();
        }

        if (Button3 == "O" && Button6 == "O" && Button9 == "O") {

            display.setText("Player O wins!!!");
            disableButtons();
        }

    }

    /**
     * Creates new form TicTacToe
     */
    public TicTacToe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bn1 = new javax.swing.JButton();
        bn2 = new javax.swing.JButton();
        bn3 = new javax.swing.JButton();
        bn4 = new javax.swing.JButton();
        bn5 = new javax.swing.JButton();
        bn6 = new javax.swing.JButton();
        bn7 = new javax.swing.JButton();
        bn8 = new javax.swing.JButton();
        bn9 = new javax.swing.JButton();
        display = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bn1.setText("-");
        bn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn1ActionPerformed(evt);
            }
        });

        bn2.setText("-");
        bn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn2ActionPerformed(evt);
            }
        });

        bn3.setText("-");
        bn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn3ActionPerformed(evt);
            }
        });

        bn4.setText("-");
        bn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn4ActionPerformed(evt);
            }
        });

        bn5.setText("-");
        bn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn5ActionPerformed(evt);
            }
        });

        bn6.setText("-");
        bn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn6ActionPerformed(evt);
            }
        });

        bn7.setText("-");
        bn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn7ActionPerformed(evt);
            }
        });

        bn8.setText("-");
        bn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn8ActionPerformed(evt);
            }
        });

        bn9.setText("-");
        bn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn9ActionPerformed(evt);
            }
        });

        display.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        display.setText("TicTacToe");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bn7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bn8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bn9, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bn4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bn5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bn6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bn1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bn2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bn3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bn1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bn2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bn3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bn4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bn5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bn6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bn7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bn8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bn9, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn1ActionPerformed
        // TODO add your handling code here:
        bn1.setText(StartGame);
        chooseAPlayer();
        bn1.setEnabled(false);
        gameOptions();
    }//GEN-LAST:event_bn1ActionPerformed

    private void bn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn2ActionPerformed
        // TODO add your handling code here:
        bn2.setText(StartGame);
        chooseAPlayer();
        bn2.setEnabled(false);
        gameOptions();
    }//GEN-LAST:event_bn2ActionPerformed

    private void bn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn3ActionPerformed
        // TODO add your handling code here:
        bn3.setText(StartGame);
        chooseAPlayer();
        bn3.setEnabled(false);
        gameOptions();
    }//GEN-LAST:event_bn3ActionPerformed

    private void bn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn4ActionPerformed
        // TODO add your handling code here:
        bn4.setText(StartGame);
        chooseAPlayer();
        bn4.setEnabled(false);
        gameOptions();
    }//GEN-LAST:event_bn4ActionPerformed

    private void bn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn5ActionPerformed
        // TODO add your handling code here:
        bn5.setText(StartGame);
        chooseAPlayer();
        bn5.setEnabled(false);
        gameOptions();
    }//GEN-LAST:event_bn5ActionPerformed

    private void bn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn6ActionPerformed
        // TODO add your handling code here:
        bn6.setText(StartGame);
        chooseAPlayer();
        bn6.setEnabled(false);
        gameOptions();
    }//GEN-LAST:event_bn6ActionPerformed

    private void bn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn7ActionPerformed
        // TODO add your handling code here:
        bn7.setText(StartGame);
        chooseAPlayer();
        bn7.setEnabled(false);
        gameOptions();
    }//GEN-LAST:event_bn7ActionPerformed

    private void bn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn8ActionPerformed
        // TODO add your handling code here:
        bn8.setText(StartGame);
        chooseAPlayer();
        bn8.setEnabled(false);
        gameOptions();
    }//GEN-LAST:event_bn8ActionPerformed

    private void bn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn9ActionPerformed
        // TODO add your handling code here:
        bn9.setText(StartGame);
        chooseAPlayer();
        bn9.setEnabled(false);
        gameOptions();
    }//GEN-LAST:event_bn9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bn1;
    private javax.swing.JButton bn2;
    private javax.swing.JButton bn3;
    private javax.swing.JButton bn4;
    private javax.swing.JButton bn5;
    private javax.swing.JButton bn6;
    private javax.swing.JButton bn7;
    private javax.swing.JButton bn8;
    private javax.swing.JButton bn9;
    private javax.swing.JLabel display;
    // End of variables declaration//GEN-END:variables
}
