/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day7;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 *
 * @author jlapi
 */
public class GuessingGame extends javax.swing.JFrame {

    /**
     * Creates new form GuessingGame
     */
    public GuessingGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDisplay = new javax.swing.JTextField();
        jButton = new javax.swing.JButton();
        lblOutput = new javax.swing.JLabel();
        lblOutput2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDisplay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton.setText("GUESS");
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        lblOutput.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblOutput2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblOutput2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOutput2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String SecretWord = "";
    private String OutputName = "";
    boolean guessMove = false;
    int lives = 0;
    char letter;

//    int[] count = new int[10];
//    int length = SecretWord.length();
    public void CheckLetter(String name, char letter) {

        int indexOfLetter = name.indexOf(letter);

        if (indexOfLetter == -1) {
            lblOutput.setText("Letters not found!");
        } else {
            lblOutput.setText("You guessed " + (indexOfLetter + 1) + ". letter");
        }

    }

    public void MatchedLetterCount(String name, String name2) {

        int counter = 0;
        for (int i = 0; i < name.length(); i++) {
            if (name.charAt(i) == name2.charAt(i)) {
                counter++;
            }
            lblOutput.setText("Sorry! You are wrong!But you guessed " + counter + " letters location");

        }
    }

    public void CommonCharFromTwoStrings(String name1, String name2) {
        Set<String> str = new HashSet<String>();
        for (int i = 0; i < name1.length(); i++) {
            for (int j = 0; j < name2.length(); j++) {
                if (name1.charAt(i) == name2.charAt(j)) {
                    str.add(name1.charAt(i) + " ");
                }
            }
        }
        lblOutput2.setText("Your guessed letters are: " + str);
    }


    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        // TODO add your handling code here:

        if (guessMove == false) {
            SecretWord = jDisplay.getText();
            int length = SecretWord.length();
            for (int i =0; i < length; i++){
                
                OutputName += "_ ";
            }
            lblOutput2.setText(OutputName);
            jButton.setText("Guess the word");
            jDisplay.setText("");
            lblOutput.setText("Word consists of " + SecretWord.length() + " letters");
            guessMove = true;
            lives = 5;

        } else {
            if (jDisplay.getText().equals(SecretWord)) {
                lblOutput.setText("BINGO!");
                lblOutput2.setText("");
                guessMove = false;
                jButton.setText("Enter the word");

            } else if (!jDisplay.getText().equals(SecretWord)) {

//                letter = jDisplay.getText().charAt(0);

//                MatchedLetterCount(SecretWord, jDisplay.getText());

//                CommonCharFromTwoStrings(SecretWord, jDisplay.getText());

//                CheckLetter(SecretWord, letter);

                OutputName = ToolsForGame.compare(jDisplay.getText(), SecretWord);
                lblOutput.setText(OutputName);
                jDisplay.setText("");
                lives--;
                
                
                if (lives == 0) {
                    guessMove = false;
                    jButton.setText("Enter the word");
                    lblOutput2.setText("");
                    lblOutput.setText("GAME OVER!");
                }

            }
        }


    }//GEN-LAST:event_jButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuessingGame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton;
    private javax.swing.JTextField jDisplay;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JLabel lblOutput2;
    // End of variables declaration//GEN-END:variables
}
